# =======================
# Settings
# =======================
PYTHON ?= python3
VENV    := .venv
BIN     := $(VENV)/bin
PIP     := $(BIN)/pip
PY      := $(BIN)/python

ENTRY ?= agent.py          # твой основной файл
REQ_FILE ?= requirements.txt

IMAGE_NAME ?= rl-trading-agent
IMAGE_TAG  ?= latest
DOCKERFILE ?= Dockerfile

# Прокинь параметры так: make run ARGS="--epochs 200 --seed 42"
ARGS ?=

.DEFAULT_GOAL := help

# =======================
# Help
# =======================
help:  ## Show help
	@grep -E '^[.a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	awk 'BEGIN {FS=":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

# =======================
# Env & deps
# =======================
venv: ## Create virtualenv
	$(PYTHON) -m venv $(VENV)

install: venv ## Install dependencies
	$(PIP) install -U pip
	@if [ -f $(REQ_FILE) ]; then $(PIP) install -r $(REQ_FILE); else echo "No $(REQ_FILE) found"; fi

dev: install ## Install dev tools if present
	@if [ -f requirements-dev.txt ]; then $(PIP) install -r requirements-dev.txt; fi
	@if [ -x "$(BIN)/pre-commit" ]; then $(BIN)/pre-commit install || true; fi

freeze: ## Freeze exact versions
	$(PIP) freeze > requirements.lock.txt

# =======================
# Run / Train / Infer
# =======================
run: ## Run agent.py (ENTRY)
	@if [ -f $(ENTRY) ]; then $(PY) $(ENTRY) $(ARGS); else echo "No $(ENTRY) found"; exit 1; fi

train: ## Train (same entry; pass ARGS if needed)
	$(MAKE) run ARGS='$(ARGS)'

infer: ## Inference / backtest (same entry; pass ARGS)
	$(MAKE) run ARGS='$(ARGS)'

# =======================
# Quality (optional)
# =======================
format: ## Format with black (if installed)
	@if [ -x "$(BIN)/black" ]; then $(BIN)/black $(ENTRY) src tests 2>/dev/null || true; else echo "black not installed"; fi

lint: ## Lint with ruff (if installed)
	@if [ -x "$(BIN)/ruff" ]; then $(BIN)/ruff check $(ENTRY) src tests || true; else echo "ruff not installed"; fi

test: ## Run tests (pytest) if available
	@if [ -x "$(BIN)/pytest" ]; then $(BIN)/pytest -q -k "not slow"; else echo "pytest not installed"; fi

test-full: ## Run full test suite
	@if [ -x "$(BIN)/pytest" ]; then $(BIN)/pytest; else echo "pytest not installed"; fi

# =======================
# Clean
# =======================
clean: ## Clean autogenerated files
	rm -rf dist build *.egg-info
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

clean-tmp: ## Clean tmp and checkpoints
	rm -rf tmp/**
	find . -type f -name "*.pt" -delete

# =======================
# Git helpers
# =======================
sync: ## Pull from origin/main
	git pull
	git pull origin main

# =======================
# Docker (optional)
# =======================
docker-build: ## Build docker image
	docker build -f $(DOCKERFILE) -t $(IMAGE_NAME):$(IMAGE_TAG) .

docker-run: ## Run image and execute agent.py
	docker run --rm -it -v $$(pwd):/app -w /app $(IMAGE_NAME):$(IMAGE_TAG) $(PYTHON) $(ENTRY) $(ARGS)

docker-shell: ## Open bash in the image
	docker run --rm -it -v $$(pwd):/app -w /app $(IMAGE_NAME):$(IMAGE_TAG) /bin/bash

eval: ## Evaluate / backtest the trained model
	$(PY) agent.py --mode eval
